# my global config
global:
  scrape_interval:     10s # By default, scrape targets every 15 seconds.
  evaluation_interval: 10s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
#rule_files:
# - "alert.rules"
# - "first.rules"
# - "second.rules"

# alerting:
#   alertmanagers:
#   - scheme: http
#     static_configs:
#     - targets:
#       - "127.0.0.1:9093"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'grafana'
    dns_sd_configs:
      - names:
        - 'grafana'
        type: 'A'
        port: 3000
        refresh_interval: 10s

  - job_name: 'mysql'
    dns_sd_configs:
      - names:
        - 'mysqld-exporter'
        type: 'A'
        port: 9104
        refresh_interval: 10s

  - job_name: 'loki'
    dns_sd_configs:
      - names:
        - 'loki'
        type: 'A'
        port: 3100
        refresh_interval: 10s

scrape_configs:
  - job_name: 'node'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['192.168.1.102:9100','localhost:9100'] 



 # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'snmp'
    static_configs:
      - targets:
        - 127.0.0.1  # SNMP device.
    metrics_path: /snmp
    params:
      module: [if_mib]
    relabel_configs:
      - source_labels: [_address_]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: _address_
        replacement: 127.0.0.1:9116